### ISSUE TITLE
Ein/Ausblenden Musterlösungen

### ISSUE THREAD

**Issue by DLND8** [ResearchMethods-ZHAW/HS22#4]

**Comment by DLND8** [comment]
Done with the following code:

```
execute: 
  echo: false   # set to true to show musterlösung
  output: false
code-fold: true
code-summary: "Musterlösung"
```
